### ISSUE TITLE
Add possibility to add free text comment

### ISSUE THREAD

**Issue by sieldep** [RADar-AZDelta/Keun#121]
In kader van 4-ogen principe: zo kan je als eerste reviewer een comment toevoegen als je bijvoorbeeld twijfelt ivm een bepaalde code. Zo kan een tweede reviewer makkelijker de mapping controleren.

**Comment by BostoenToby** [comment]
Er kan momenteel een comment toegevoegd worden in de mapping pop-up.
Hiervoor moet je de detail openklappen en hier zijn er opties om de equivalence aan te passen of een reviewer & comments toe te voegen.

![image](https://github.com/RADar-AZDelta/Keun/assets/71939691/a6d8ff62-1612-4095-b307-e39ea39c1581)

**Comment by sieldep** [comment]
Ok, super! Louise en ik hadden hierover gekeken.
