### ISSUE TITLE
Custom concept: concept_code from sourceCode

### ISSUE THREAD

**Issue by sieldep** [RADar-AZDelta/Keun#127]
Bij het exporteren van custom concepts, wordt in de file _concept.csv in de kolom concept_code de sourceNeme ingevuld als code. Eigenlijk zou dit de sourceCode kolom moeten zijn.

**Comment by BostoenToby** [comment]
Zou het kunnen dat u dit verkeerd hebt gezien?
Als ik dit test & in de code bekijk is het steeds de sourceCode die toegekent wordt aan de concept_code.

**Comment by sieldep** [comment]
Heb het nog eens nagekeken en opnieuw gemapt, maar het is toch het verkeerde dat wordt toegkend: 
![image](https://github.com/RADar-AZDelta/Keun/assets/117644339/3e934da8-8065-4e2a-99a2-c6ff7dfbd0e1)
Op deze zie je dat de sourceCode AZD_HiX_epd_..... is, maar bij het downloaden van de file staat er dan Cardiaal onder concept_code: 
![image](https://github.com/RADar-AZDelta/Keun/assets/117644339/ed044abc-c24a-4b6c-881f-e45bdeac7966)
