### ISSUE TITLE
Keun - delete button in concept not working

### ISSUE THREAD

**Issue by sieldep** [RADar-AZDelta/Keun#143]
![image](https://github.com/RADar-AZDelta/Keun/assets/117644339/c16ab6a8-b61f-4dae-9a0b-7df464240987)
Wanneer ik hier op de X klik bij een concept dat ik eerst met de plus had toegevoegd, wordt het concept in plaats van verwijderd, nogmaals toegevoegd aan de lijst met mapped concepten. Kan je dit bekijken?

**Comment by BostoenToby** [comment]
De buttons met het X-icoon & het vlag icoon zijn bedoeld om de status te veranderen naar "FLAGGED" of "UNAPPROVED". Dit heb ik erbij geplaatst naar aanvraag van Louise. https://github.com/RADar-AZDelta/Keun/issues/128

Haar vraag was om enkel een rij te flaggen in de pop-up, maar ik heb ook direct een button voorzien om de rij "UNAPPROVED" te maken.

Ik stel één van volgende zaken voor:

- [ ] Een extra knop met een prullenbak toe te voegen om de rij opnieuw unmapped te maken
- [ ] De knop met "X" icoon te vervangen naar een delete knop
- [ ] De knop met "X" icoon te verwijderen

**Comment by sieldep** [comment]
Hoi Toby, 
Ik had het verkeerd gezien, omdat ik uiteindelijk het concept geflagged had en dan de rij in geel kwam in de tabel (en ik daardoor het rood van unapprove niet had gezien). De knoppen mogen zeker hetzelfde blijven, enkel zag ik nog het volgende probleem:
![image](https://github.com/RADar-AZDelta/Keun/assets/117644339/9fd39975-4d22-40d1-b92c-3bca759467f6)
Wanneer ik eerst het concept toevoeg via de plus, wordt het plusje groen. Als ik daarna dan toch op het kruisje klik, blijft het plusje groen, zodat het lijkt alsof dat concept nog steeds 'approved' is. Kan je eventueel het kruisje dan rood maken? Ik zie dat het kruisje wel rood wordt, wanneer ik in de table view het concept 'UNAPPROVE'. 
Het andere dat ik zag: ik klikte meermaals op het kruisje en het plusje omdat ik niet zeker was dat het nu effectief op 'UNAPPROVE' stond. Elke keer dat ik op 1 van de 2 klikte, kwam er een nieuwe rij bij voor dat concept_id in het overzicht met de mapped concepts (zie onder). Eigenlijk zou hetzelfde concept_id er max 1 keer mogen staan. 
![image](https://github.com/RADar-AZDelta/Keun/assets/117644339/ed3c846a-57ff-4f9c-a0ce-88c5ff446465)

**Comment by BostoenToby** [comment]
Bedankt om deze bug door te geven, ik kijk om het zo snel mogelijk op te lossen.

**Comment by BostoenToby** [comment]
Zou het kunnen dat in uw settings "Map to multiple concepts" aanstaat? Dat zou de issue met de mapped concepts table verklaren.

**Comment by sieldep** [comment]
Ja, klopt, deze staat inderdaad aan. Ok, dan weet ik dat her daaraan ligt!

**Comment by BostoenToby** [comment]
Ik zal er wel voor zorgen dat een bepaalde row van Athena niet tweemaal kan gemapt worden aan een row als het dezelfde is. Momenteel kan je bijvoorbeeld athenaRow met id "1234" zowel flaggen, unapproved & approven aan een row wat ervoor zorgt dat er duplicaten zijn. Dus dat zal ik oplossen

**Comment by sieldep** [comment]
Ok, perfect! Dank je wel :)
