### ISSUE TITLE
Comments for a concept

### ISSUE THREAD

**Issue by sieldep** [RADar-AZDelta/Keun#171]
Hoi Toby, 
Wanneer er een comment is toegevoegd vanuit de table view (zie onder), is deze comment niet zichtbaar in het Comments veld wanneer je het concept opendoet. Zou dit mogelijk zijn? Of zouden we dit toch beter apart houden? 

![image](https://github.com/RADar-AZDelta/Keun/assets/117644339/245cf343-fef4-484c-9034-554b21eb058e)
![image](https://github.com/RADar-AZDelta/Keun/assets/117644339/e11a7170-5d32-4c0d-a09b-4202108eea53)

**Comment by BostoenToby** [comment]
Dag Siel,
Het is zeker mogelijk om de toegevoegde comment ook in de pop-up zichtbaar te maken. 
Bij de volgende push zal ik deze feature verwerken.

**Comment by sieldep** [comment]
Super, dank je wel. Geen haast hiervoor!
