### ISSUE TITLE
Automatically flag custom concepts

### ISSUE THREAD

**Issue by lbertelo01** [RADar-AZDelta/Keun#188]
Since the [omop procedures](https://github.com/RADar-AZDelta/radar_procedures/blob/main/data/OMOP_review_procedures.md) ask to flag custom concepts, it would be useful if Keun does this automatically instead of putting a new custom concept to SEMI-APPROVED.

**Comment by BostoenToby** [comment]
The possibility was added to approve, flag or unapprove a custom concept.
