### ISSUE TITLE
missing vocabulary names and no class names in overview

### ISSUE THREAD

**Issue by hannevanl** [RADar-AZDelta/Keun#193]
Soms staat de vocabulary niet ingevuld en de class name staat ook nooit ingevuld.

![image](https://github.com/RADar-AZDelta/Keun/assets/144660813/a7648a2b-1699-4038-ad10-07fcad9825cf)

**Comment by BostoenToby** [comment]
De vocabulary & className zijn in de volgende versie zichtbaar
