### ISSUE TITLE
custom codes dubbel gegenereerd

### ISSUE THREAD

**Issue by Joica** [RADar-AZDelta/Keun#195]
Uit deze file 
![image](https://github.com/RADar-AZDelta/Keun/assets/144668554/f4bd1d2b-8fd1-4a28-87db-b399d5d2181d)

![image](https://github.com/RADar-AZDelta/Keun/assets/144668554/8ed0ac7b-4af7-4c4b-9d49-c3b5bf772e2b)
Normaalgezien 11 custom codes:
![image](https://github.com/RADar-AZDelta/Keun/assets/144668554/4fc86be8-4a18-42c1-a129-e5d7a7083a7b)

Er komen er dubbel uit:
![image](https://github.com/RADar-AZDelta/Keun/assets/144668554/cee30970-c11b-41c8-ba61-35ca44298c69)

File output customs:
[Metingen_meting_usagi_concept.csv](https://github.com/RADar-AZDelta/Keun/files/14422872/Metingen_meting_usagi_concept.csv)

**Comment by BostoenToby** [comment]
Dit kwam doordat er in het begin, tijdens het inladen van de file, alle custom rows overlopen werden. Deze werden dan toegevoegd in de custom file dus hierdoor de dubbels
