### ISSUE TITLE
Do not allow empty values for required fields of custom concepts.

### ISSUE THREAD

**Issue by pjlammertyn** [RADar-AZDelta/Keun#196]
Some fields are required for custom concepts:

![image](https://github.com/RADar-AZDelta/Keun/assets/1187178/73bf3340-8d06-400c-b68a-91c0698af774)

So Keun must NOT allow empty values for those required fields!

![image](https://github.com/RADar-AZDelta/Keun/assets/1187178/de5b3bc9-593e-4f43-9e75-1eef11336bb5)

**Comment by pjlammertyn** [comment]
ga eerst een kijken of ik dit kan afvangen in RiaB

**Comment by BostoenToby** [comment]
Zal er rekening mee houden bij de herwerking van custom concepts

**Comment by pjlammertyn** [comment]
kan dit opvangen in RiaB
