### ISSUE TITLE
Comments get deleted if mapping changes

### ISSUE THREAD

**Issue by lbertelo01** [RADar-AZDelta/Keun#197]
Is it possible to keep the comments even if the mapping changes? If you change a mapping (e.g. during a review, you suggest a better concept), the previous comments on that concept get deleted. 
It would be good if they are kept, especially for team data if they review the remaining flagged concepts on which multiple comments were given.

Thanks!

**Comment by BostoenToby** [comment]
The comments are kept after remapping of a concept
