### ISSUE TITLE
KEUN; COMMENT issue in detailview

### ISSUE THREAD

**Issue by kdenturc** [RADar-AZDelta/Keun#199]
If you switch between concepts in detailview than comment from previous datapoint will appear
If you want to add this comment, I need to click enter
But if you do this 5 times, you end up with 5 enters in your _usagi.csv download, which gives bugs 
![image](https://github.com/RADar-AZDelta/Keun/assets/98580512/8636cf94-f5f6-428f-b6f1-98b0cdbb3701)

would be nice to remove the enters in your download
tx!

**Comment by BostoenToby** [comment]
This issue has been fixed. If you place an enter in your comment text, this will replace this with a space in the row.
