### ISSUE TITLE
KEUN; check for domainID in automapping

### ISSUE THREAD

**Issue by kdenturc** [RADar-AZDelta/Keun#200]
@BostoenToby 
RiAB version 0.038 is online and does a check on FK domains with concepts
(vb gender_concept_id van person tabel, moet van het domain 'Gender' zijn)
[CommonDataModel/inst/csv/OMOP_CDMv5.4_Field_Level.csv at main · OHDSI/CommonDataModel (github.com)](https://github.com/OHDSI/CommonDataModel/blob/main/inst/csv/OMOP_CDMv5.4_Field_Level.csv)

if you have automapping on, it can occur that other domains are chosen, and even if it is UNCHECKED, it gives errors in the run RiAB, would be nice to have a filter for this in your download or automapping...

tx!

**Comment by BostoenToby** [comment]
Let the user set a certain domain for a Keun file & the automapping will make sure that it picks a concept with the correct domainId

**Comment by BostoenToby** [comment]
I've added this new feature in the newest version of Keun.
