### ISSUE TITLE
Bug in custom concepts

### ISSUE THREAD

**Issue by sieldep** [RADar-AZDelta/Keun#202]
Hoi Toby, 
Bij deze file [moc_usagi (5).csv](https://github.com/RADar-AZDelta/Keun/files/14463049/moc_usagi.5.csv) heb ik een probleem met de custom concepts. 
Als ik de file wil downloaden, krijg ik geen tweede bestand voor de customs, terwijl er wel redelijk wat inzitten. 
Daarnaast als ik kijk naar een goedgekeurd custom concept, staat de custom concept als false en staat er niets onder de tab custom.
![image](https://github.com/RADar-AZDelta/Keun/assets/117644339/f8044e09-adde-4f49-a97d-666b01d1146e)

Een idee hoe dit zou komen? Louise heeft geen problemen met deze file.

**Comment by BostoenToby** [comment]
Deze issue zal aangepakt worden in de nieuwe versie van Keun.
De custom concepten worden op een andere manier aangepakt waarbij ze onafhankelijk van de rij worden opgeslagen. Dit zal ervoor zorgen dat ze ook hergebruikt zullen kunnen worden.
Normaal zal deze versie ten laatste vrijdag (08/03) uitkomen.

**Comment by sieldep** [comment]
Ok, super! Bedankt, Toby!

**Comment by BostoenToby** [comment]
Door de verandering in werking van custom concepts is dit opgelost.
