### ISSUE TITLE
flagged concepten extra extraheren uit Keun

### ISSUE THREAD

**Issue by cdeltomm00** [RADar-AZDelta/Keun#204]
Graag willen wij de flagged concepten uit een file kunnen extraheren (zonder dat ze daarbij weg zijn uit de originele file)

**Comment by BostoenToby** [comment]
Deze feature is toegevoegd in de nieuwe versie van Keun

**Comment by BostoenToby** [comment]
Deze feature is zoals eerder vermeld toegevoegd, maar ik zal deze momenteel nog niet in productie steken. Ik kan momenteel niet 100% garanderen dat deze feature perfect zal werken dus daarvan dat ik deze issue terug open.
In de komende dagen zal ik hier wel verder aan werken om dit wel te kunnen garanderen.

**Comment by BostoenToby** [comment]
De feature is toegevoegd in de nieuwe versie!
