### ISSUE TITLE
Fuzzy search issue after editing custom concept

### ISSUE THREAD

**Issue by Joica** [RADar-AZDelta/Keun#301]
When adding a custom concept, it's visible in Keun, but if I edit an existing custom concept it doesn't. It will still show the old custom concept with that id and I think that it will only show the updated version of the concept if I restart the backend.

Can this be checked if there is a way to update the custom concept?

In search of Keun:
<img width="705" alt="image" src="https://github.com/user-attachments/assets/b1f515ae-61fc-4059-952d-2f13e48926b5">

In BigQuery:
<img width="527" alt="image" src="https://github.com/user-attachments/assets/97f553ce-eca6-43b8-920e-d3f9978be492">

In Parquet file (transformed to JSON):
<img width="602" alt="image" src="https://github.com/user-attachments/assets/e5308775-eb00-4b05-9f10-6d0dd931526d">

**Comment by pjlammertyn** [comment]
Simulating this on the inno-linux, shows that it works on linux
![image](https://github.com/user-attachments/assets/5d23ff18-6f2c-411f-a293-c4c5a5b6bf53)
Must be a Windows problem

**Comment by pjlammertyn** [comment]
![image](https://github.com/user-attachments/assets/97fa5d4d-3ada-48d8-a42b-d4b519499cd0)
