### ISSUE TITLE
Enhancement: via hiërarchie kunnen zoeken in de vocabularies

### ISSUE THREAD

**Issue by cdeltomm00** [RADar-AZDelta/Keun#302]
Ik zoek vaak nog via de athena site omdat je daar via hiërarchie kunt doorklikken naar concepten en ik kom vaak op die manier tot het juiste concept. Ik weet niet als er een mogelijkheid is om dit evt in te bouwen in onze Keun?

**Comment by BostoenToby** [comment]
Deze issue is geopend in de toebehorende Keun repository
