### ISSUE TITLE
popup to close comes first en then the savedialog

### ISSUE THREAD

**Issue by pjlammertyn** [RADar-AZDelta/Keun#51]

**Comment by BostoenToby** [comment]
![image](https://github.com/RADar-AZDelta/Keun/assets/71939691/64ab976f-0d7d-4748-80e6-df3ca767094e)
Not sure if it is possible to invoke the showSaveFilePicker first and then the pop-up

**Comment by pjlammertyn** [comment]
can't you async await the saveToFile() method?

**Comment by pjlammertyn** [comment]
nope async wont work

**Comment by pjlammertyn** [comment]
best then to remove the saveToFile dialog

**Comment by pjlammertyn** [comment]
also Gecko based browsers:

```js
window.addEventListener("beforeunload", (e) => {
  const confirmationMessage = "\\o/";

  // Gecko + IE
  (e || window.event).returnValue = confirmationMessage;

  // Safari, Chrome, and other WebKit-derived browsers
  return confirmationMessage;
});

```
